steps:
  - name: Set docroot.
    plugin: LAMPApp
    subDirectory: _site
  - name: Update system.
    plugin: Script
    script:
      - gem uninstall bundler
      - apt-get update
  - name: Install Imagemagick.
    plugin: Script
    script:
      - apt-get install -y software-properties-common imagemagick
      - apt-add-repository -y ppa:brightbox/ruby-ng
      - apt-get update
  - name: Install Ruby 2.3.
    plugin: Script
    script:
      - apt-get install -y ruby2.3 ruby2.3-dev
      - update-alternatives --config ruby
      - gem install bundler
  - name: Install Jekyll build Dependencies.
    plugin: Script
    script:
      - cd $SRC_DIR
      - bundle install --path vendor/bundle
  - name: Build Jekyll site
    plugin: Script
    script:
      - locale-gen en_US.UTF-8
      - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 bundle exec jekyll build --destination=/var/www/html
