# Syntax highlighting
highlighter:         pygments

# Permalinks
#
permalink:           pretty

# Setup
title:               Probo Jekyll Example
tagline:             Basic example of a Jekyll powered GitHub Pages site with Sass enabled.
url:                 http://probo-demos.github.io/probo-example-jekyll
baseurl:             

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
