# Syntax highlighting
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Probo Jekyll Example
tagline:             Basic example of a Jekyll site with Sass enabled.
url:                 http://probo-demos.github.io/probo-example-jekyll
baseurl:             

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
